name: Build & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Make
        run: sudo apt-get install make

      - name: Build
        run: make

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./roundcubemail-1.7-git.tar.gz

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-complete
          path: ./roundcubemail-1.7-git-complete.tar.gz
